### ISSUE TITLE
error: unknown type name 'NAPI_C_CTOR'

### ISSUE THREAD

**Issue by tuler** [ajihyf/node-addon-api-helper#1]
When trying to use with `node-addon-api@8` I get a `unknown type name 'NAPI_C_CTOR'`

I guess this is not compatible with `node-addon-api@8`.
If that is the case it would be nice to have that information in the README.

**Comment by ajihyf** [comment]
Hi, thank you for reporting this issue. It's not related to the version of `node-addon-api` but stems from changes made in Node.js version 20. This [MR](https://github.com/nodejs/node/pull/46319/files#diff-1a7a14ecb8ebcfadce2b39d74f174b946745bf6970291ea7be17399b7bbca3d5) has removed an internal macro that I [ab]used before. I'll be working on a bugfix shortly.

**Comment by ajihyf** [comment]
@tuler Just published v2.2.0 which should be compatialble with all Node.js LTS versions.
